# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/blobslayer',
                'doc_host': 'https://tutankalex.github.io',
                'git_url': 'https://github.com/tutankalex/blobslayer',
                'lib_path': 'blobslayer'},
  'syms': {'blobslayer.core': {'blobslayer.core.foo': ('core.html#foo', 'blobslayer/core.py')}}}
