# generated by datamodel-codegen:
#   filename:  file-metadata.schema.json
#   timestamp: 2023-12-11T04:45:43+00:00

from __future__ import annotations

from pydantic import BaseModel


class FileMetadataSchema(BaseModel):
    blobKey: str
